version: '3.8'

services:
  postgres:
    image: postgres:17.3
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: memory_cards
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: memory_cards
    networks:
      - tg_bot_network
    volumes:
      - ~/postgresql_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

networks:
  tg_bot_network:
    external: true