version: '3.8'

services:
  postgres:
    image: postgres:17.3
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: memory_cards
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: memory_cards
    networks:
      - tg_bot_network
    volumes:
      - ~/postgresql_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    pid: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - tg_bot_network
    ports:
      - "127.0.0.1:9090:9090"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    networks:
      - tg_bot_network
    command:
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|run)($|/)"
    volumes:
      - /:/host:ro
    ports:
      - "127.0.0.1:9100:9100"
    environment:
      - NODE_EXPORTER_TEXTFILE_DIR=/host

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    networks:
      - tg_bot_network
    volumes:
      - ~/grafana:/var/lib/grafana
    ports:
      - "127.0.0.1:3000:3000"

networks:
  tg_bot_network:
    external: true