package com.example.memcards.telegram;

public enum CallbackAction {
    SET_LANGUAGE,
    SELECT_COLLECTION,
    SELECT_COLLECTION_FOR_CARD,
    FOCUS_ON_COLLECTION,
    SELECT_COLLECTION_PAGE,
    EDIT_COLLECTION_CARDS,
    DELETE_COLLECTION,
    CONFIRM_CARD_CREATION,
    CHANGE_CARD_COLLECTION
}
