# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

#  run-app:
#    needs: build
#    runs-on: self-hosted
#    permissions:
#      contents: read
#
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 23
#        uses: actions/setup-java@v4
#        with:
#          java-version: '23'
#          distribution: 'temurin'
#      - name: Verify JAR existence
#        run: ls -R build/libs
#
#      - name: Stop all running Java processes
#        run: |
#          echo "Killing all running Java processes..."
#          pkill -f java || echo "No Java processes running."
#
#      - name: Run in a job (to be removed)
#        run: java -jar build/libs/memory-cards-0.0.1-SNAPSHOT.jar
#
#      - name: Start application in background
#        run: |
#          echo "Starting application in background with nohup..."
#          nohup java -jar build/libs/memory-cards-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
#
#      - name: Start Check
#        env:
#          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
#        run: |
#          echo "Performing health check..."
#          sleep 20  # Letting the app to start
#          if pgrep -f memory-cards-0.0.1-SNAPSHOT.jar > /dev/null; then
#            echo "Application is running."
#          else
#            echo "Application failed to start."
#            exit 1
#          fi

  build:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Build with Gradle Wrapper
      run: ./gradlew build
    - name: Verify JAR existence
      run: ls -R build/libs

    - name: Stop all running Java processes
      run: |
        echo "Killing all running Java processes..."
        pkill -f java || echo "No Java processes running."

    - name: Run in a job (to be removed)
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: java -jar build/libs/memory-cards-0.0.1-SNAPSHOT.jar

#  dependency-submission:
#    runs-on: self-hosted
#    permissions:
#      contents: write
#
#    steps:
#    - uses: actions/checkout@v4
#    - name: Set up JDK 23
#      uses: actions/setup-java@v4
#      with:
#        java-version: '23'
#        distribution: 'temurin'
#
#    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
#    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
#    - name: Generate and submit dependency graph
#      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
